### ISSUE TITLE
Determine what to do with 8-bit bytes in 7-bit message bodies

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/MailLib#1]
Some email messages contain un-encoded 8-bit bytes in the message body and declare
a "content-transfer-encoding" of `7bit` (making those bytes invalid).  The code currently
handles this as follows:
- In the following cases, any 8-bit bytes are replaced with question marks:
  - In the prologue and epilogue of multipart messages
  - In messages without a MIME-Version header field
  - In messages with a content type of "text/plain"
- In the following cases, an error is thrown if 8-bit bytes are encountered:
  - If the message has a content type other than "text/plain", including "text/html".

In particular, the code currently throws an exception if 8-bit bytes are found in a `7bit` "text/html" message, since replacing the bytes with question marks might be a security risk in "text/html" messages.  Although replacing the bytes with the replacement character (U+FFFD) would be less of a risk, my parser is byte-oriented rather than character-oriented when it comes to parsing message bodies, and the replacement character requires more than one byte in UTF-8.

However, in many cases, the charset declared is single-byte, such as "us-ascii" or "iso-8859-1", so treating the content as 8-bit instead might be better.

In view of all this, what is the best way to handle these cases?

**Comment by jstedfast** [comment]
Just always assume 8-bit for any textual body, using the charset defined, or, if none is defined use a fallback approach starting with UTF-8 (if it isn't UTF-8, it won't properly convert anyway) and, if that fails, fall back to ISO-8859-1.

If you want to get even more sophisticated, have your library allow the developer to override the System.Text.Encoding used to convert the text. This allows the developer to offer the end-user a drop-down menu of charsets that the user can then select if iso-8859-1 does not display correctly (e.g. the text body is in undeclared koi8-r).

FWIW, I have my own MIME parser that is also byte based rather than character based and handles undeclared charsets in both the headers and bodies: [MimeKit](https://github.com/jstedfast/MimeKit).

BT, kudos on using a tokenizer approach rather than what most everyone else has done which is to use String.IndexOf() and Regex hacks that kinda-sorta-but-don't-really work.
